version: '3.9'
services:

  fastapi:
    container_name: fastapi
    build: 
      context: ./FastAPI
      dockerfile: ./Dockerfile
    ports:
     - 8010:8010
  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

    ports:
      - 9091:9091