services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9091:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3001:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
  fastapi:
    container_name: fastapi
    build: 
      context: ./FastAPI
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=postgres
      - ALLOW_VPN=False
      - POSTGRES_HOST=postgres:5432
      - DATABASE_IP=http://gql_ug:8000/gql
      - LOG_SERVER=localhost
      - LOG_PORT=514
      - TOKEN_LIFE_LIMIT=3600
      - LOG_SERVER=syslog-ng
      - LOG_PORT=514g
    ports:
     - 8010:8010
  syslog-ng:
    image:  balabit/syslog-ng:latest
    container_name: syslog-ng
    ports:
      - 601:601
      - 514:514/udp
    restart: unless-stopped
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 60s
      timeout: 10s
      retries: 5
    restart: on-failure:3
    ports:
      - 5433:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=anyone@anywhere.com
      - PGADMIN_DEFAULT_PASSWORD=example
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:80/misc/ping"]
      interval: 60s
      timeout: 10s
      retries: 5
    ports:
      - 31125:80

  app:
    build: 
      context: ./simple_frontend
      dockerfile: ./Dockerfile
    ports:
      - '3452:3452'
    environment:
      - PORT=3452
volumes:
  prom_data:
