global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9091']

  - job_name: 'fastapi'
    static_configs:
      - targets: ['fastapi:8010']
