groups:
  - name: server_alerts
    rules:
      - alert: HighRequestRate
        expr: rate(server_request_total[1m]) > 10
        for: 5m
        labels:
          severity: medium
        annotations:
          summary: High request rate
          description: The number of incoming requests surpasses 500 per minute for at least 5 minutes.
      - alert: HighFailRequestRate
        expr: rate(server_fail_request_total[1m])/rate(server_request_total[1m]) > 0.05
        labels:
          severity: high
        annotations:
          summary: High fail request rate
          description: The error rate for HTTP requests has exceeded 5% for 2m
      - alert: PossibleDoS
        expr: rate(server_request_total[1m]) > 50 and
              sum(rate(server_response_time_ms_bucket{le="250.0"}[1m]))/sum(rate(server_response_time_ms_count[1m])) > 0.5
        labels:
          severity: high
        annotations:
          summary: Possible DoS attack
          description: The number of incoming requests surpasses 3000 per minute, and the process lasted more than 250ms for 50% of the incoming requests.
      - alert: SlowProcessTime
        expr: rate(server_response_time_ms_sum[1m])/rate(server_response_time_ms_count[1m]) > 100 and histogram_quantile(0.95, sum(rate(server_response_time_ms_bucket[1m])) by (le)) < 100
        for: 2m
        labels:
          severity: medium
        annotations:
          summary: Slow processing time
          description: For 2 minutes the average response time is greater than 100ms and at least 5% of requests take longer than 100ms to process
      - alert: PossibleInjectionAttack
        expr: histogram_quantile(0.975,sum(rate(server_reponse_length_bytes_bucket[1m])) by (le)) > 3000
        labels:
          severity: high
        annotations:
          summary: Possible Injection attack
          description: Over 2.5% of incomming request are requesting more data than 3000B
      - alert: AuthenticationBreach
        expr: rate(server_authentication_rejected_total[5m])  > 0.5
        labels:
          severity: high
        annotations:
          summary: Possible breach in authentication
          description: Database rejected more than 150 requests for violating authentication rule in 5 minutes
  - name: client-alert
    rules:
      - alert: HighRequestRateClient
        expr: sum(rate(client_request_total[1m])) by (client) > 3
        for: 2m
        labels:
          severity: medium
        annotations:
          summary: "High client request rate from {{ $labels.client }}"
          description: "{{ $labels.client }} is sending requests at a rate higher than 150 requests per minute for 2 minutes."
