global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 15s
rule_files:
  - alert-rules.yaml

scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - prometheus:9090
- job_name: 'fastapi'
  static_configs:
    - targets: ['fastapi:8010']